<x-layout title="Travel Schedule">
    <div class="min-h-screen bg-[#F2F2F7] pb-[120px]">
        <x-header type="back" title="Travel schedule" />
        
        <div class="px-5 pt-6">
            <form method="POST" action="{{ route('tour.store') }}" id="tour-form">
                @csrf
                
                <!-- Hidden input for days -->
                <input type="hidden" name="days" id="selected-days" value="5">
                
                <!-- Place of Departure -->
                <div class="bg-white rounded-[10px] px-5 py-4 mb-4 flex justify-between items-center shadow-sm">
                    <div class="text-sm text-[#8e8e93]">Place of departure</div>
                    <input type="text" 
                           name="place" 
                           placeholder="Enter place" 
                           required
                           class="text-base font-medium text-[#1c1c1e] text-right border-none outline-none bg-transparent">
                </div>

                <!-- Destination -->
                <div class="bg-white rounded-[10px] px-5 py-4 mb-4 flex justify-between items-center shadow-sm">
                    <div class="text-sm text-[#8e8e93]">Destination</div>
                    <input type="text" 
                           name="destination" 
                           placeholder="Enter destination" 
                           required
                           class="text-base font-medium text-[#1c1c1e] text-right border-none outline-none bg-transparent">
                </div>

                <!-- Number of Days Selector -->
                <div class="bg-white rounded-[10px] p-5 mt-4 h-[350px] flex flex-col overflow-hidden">
                    <div class="text-base font-medium text-[#1c1c1e] px-0">number of days ?</div>
                    
                    <div class="days-selector-outer flex-grow overflow-x-scroll pt-[90px]" id="days-outer" style="scroll-snap-type: x mandatory;">
                        <div class="days-selector-inner flex items-center h-1/2 relative" id="days-selector" style="padding: 0 calc(50% - 40px);">
                            <!-- Days will be generated by JavaScript -->
                        </div>
                    </div>
                </div>

                <!-- Next Button -->
                <button type="submit" 
                        class="font-semibold text-2xl text-[#2B9BFF] bg-white border-[3px] border-[#2B9BFF] rounded-md mt-5 mb-5 cursor-pointer ml-auto block w-[120px] py-2 hover:bg-[#2B9BFF] hover:text-white transition">
                    next
                </button>

                <!-- Error Messages -->
                @if ($errors->any())
                    <div class="mt-4 p-4 bg-red-50 border border-red-200 rounded-lg">
                        <ul class="text-red-600 text-sm space-y-1">
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
            </form>
        </div>
    </div>

    <x-navigation active-page="plan" />

    <style>
        .days-selector-outer::-webkit-scrollbar {
            display: none;
        }
        
        .days-selector-outer {
            -ms-overflow-style: none;
            scrollbar-width: none;
        }
        
        .day-item {
            min-width: 80px;
            text-align: center;
            padding: 0 10px;
            font-size: 60px;
            font-weight: 700;
            color: #8e8e93;
            transition: all 0.2s ease-out;
            cursor: pointer;
            scroll-snap-align: center;
            line-height: 1;
            position: relative;
            flex-shrink: 0;
        }
        
        .day-item:not(:last-child)::after {
            content: '';
            position: absolute;
            top: 50%;
            right: 0;
            transform: translateY(-50%);
            width: 1px;
            height: 80%;
            background-color: #c6c6c6;
        }
        
        .day-item.selected {
            font-size: 90px;
            color: #1c1c1e;
            font-weight: 800;
        }
        
        .day-item.selected::after {
            background-color: transparent;
        }
    </style>

    <script>
        document.addEventListener('DOMContentLoaded', () => {
            const daysSelector = document.getElementById('days-selector');
            const daysOuter = document.getElementById('days-outer');
            const hiddenInput = document.getElementById('selected-days');
            const totalDays = 30;
            const initialDay = 5;
            let selectedDayElement = null;

            // Generate day items
            for (let i = 1; i <= totalDays; i++) {
                const dayItem = document.createElement('div');
                dayItem.classList.add('day-item');
                dayItem.textContent = i;
                dayItem.dataset.day = i;
                daysSelector.appendChild(dayItem);
            }

            // Add spacer to allow last item to be centered
            // The spacer needs to be the same width as the right padding
            const spacer = document.createElement('div');
            spacer.style.minWidth = 'calc(50% - 40px)';
            spacer.style.width = 'calc(50% - 40px)';
            spacer.style.flexShrink = '0';
            daysSelector.appendChild(spacer);

            // Center element function
            const centerElement = (targetElement) => {
                if (!targetElement) return;
                const scrollTarget = targetElement.offsetLeft - (daysOuter.offsetWidth / 2) + (targetElement.offsetWidth / 2);
                requestAnimationFrame(() => {
                    daysOuter.scrollLeft = scrollTarget;
                });
            };

            // Update selected day
            const updateSelectedDay = () => {
                let closestDay = null;
                let minDistance = Infinity;
                const containerCenter = daysOuter.scrollLeft + (daysOuter.offsetWidth / 2);

                daysSelector.querySelectorAll('.day-item').forEach(dayItem => {
                    const dayCenter = dayItem.offsetLeft + (dayItem.offsetWidth / 2);
                    const distance = Math.abs(dayCenter - containerCenter);

                    if (distance < minDistance) {
                        minDistance = distance;
                        closestDay = dayItem;
                    }
                    
                    dayItem.classList.remove('selected');
                });

                if (closestDay) {
                    closestDay.classList.add('selected');
                    selectedDayElement = closestDay;
                    hiddenInput.value = closestDay.dataset.day;
                }
            };

            // Initial setup
            const initialDayElement = daysSelector.querySelector(`[data-day="${initialDay}"]`);
            if (initialDayElement) {
                centerElement(initialDayElement);
            }

            // Scroll event
            let scrollTimeout;
            daysOuter.addEventListener('scroll', () => {
                clearTimeout(scrollTimeout);
                scrollTimeout = setTimeout(updateSelectedDay, 150);
            });

            // Click event
            daysSelector.addEventListener('click', (event) => {
                const dayItem = event.target.closest('.day-item');
                if (dayItem) {
                    centerElement(dayItem);
                    updateSelectedDay();
                }
            });

            // Initial update
            setTimeout(updateSelectedDay, 200);
        });
    </script>
</x-layout>